import { ColumnDefinition } from '../types/Column';

export const productColumns: ColumnDefinition[] = [
  { field: 'code', header: 'Code', width: '120px' },
  { field: 'name', header: 'Name', width: '200px' },
  { field: 'category', header: 'Category', width: '150px' },
  { field: 'brand', header: 'Brand', width: '150px' },
  { field: 'manufacturer', header: 'Manufacturer', width: '180px' },
  { field: 'price', header: 'Price', width: '120px' },
  { field: 'unitCost', header: 'Unit Cost', width: '120px' },
  { field: 'profitMargin', header: 'Margin (%)', width: '120px' },
  { field: 'quantity', header: 'Quantity', width: '120px' },
  { field: 'minStockLevel', header: 'Min Stock', width: '120px' },
  { field: 'maxStockLevel', header: 'Max Stock', width: '120px' },
  { field: 'reorderPoint', header: 'Reorder Point', width: '140px' },
  { field: 'leadTime', header: 'Lead Time', width: '120px' },
  { field: 'inventoryStatus', header: 'Status', width: '130px' },
  { field: 'rating', header: 'Rating', width: '130px' },
  { field: 'color', header: 'Color', width: '120px' },
  { field: 'size', header: 'Size', width: '120px' },
  { field: 'weight', header: 'Weight', width: '120px' },
  { field: 'dimensions', header: 'Dimensions', width: '130px' },
  { field: 'material', header: 'Material', width: '150px' },
  { field: 'shelfLocation', header: 'Location', width: '130px' },
  { field: 'barcode', header: 'Barcode', width: '150px' },
  { field: 'warrantyPeriod', header: 'Warranty', width: '130px' },
  { field: 'countryOfOrigin', header: 'Origin', width: '130px' },
  { field: 'packageType', header: 'Package', width: '130px' },
  { field: 'unitsPerPackage', header: 'Units/Pack', width: '120px' },
  { field: 'shippingWeight', header: 'Ship Weight', width: '130px' },
  { field: 'shippingClass', header: 'Ship Class', width: '130px' },
  { field: 'safetyStock', header: 'Safety Stock', width: '130px' },
  { field: 'seasonality', header: 'Seasonality', width: '130px' },
  { field: 'productLifecycle', header: 'Lifecycle', width: '130px' },
  { field: 'sustainabilityScore', header: 'Sustainability', width: '140px' },
  { field: 'returnRate', header: 'Return Rate', width: '130px' },
  { field: 'dateAdded', header: 'Date Added', width: '130px' },
  { field: 'lastModified', header: 'Last Modified', width: '130px' },
  { field: 'supplierName', header: 'Supplier', width: '150px' },
  { field: 'supplierContact', header: 'Supplier Contact', width: '180px' },
  { field: 'taxRate', header: 'Tax Rate', width: '120px' },
  { field: 'discountAvailable', header: 'Discount', width: '120px' },
  { field: 'handlingInstructions', header: 'Handling', width: '180px' }
];